# Generated by Django 6.0.3 on 2026-03-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('agent', 'Agent'), ('broker', 'Broker')], default='buyer', max_length=10),
        ),
    ]
