# Generated by Django 5.1.1 on 2026-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_status',
            field=models.CharField(choices=[('sale', 'For Sale'), ('sold', 'Sold')], default='sale', max_length=10),
        ),
    ]
